version: "3.8"

services:
  proxy:
    image: haproxy:2.6
    ports:
      - ${PORT}:80
      - ${PROXY_STATS_PORT}:1936
    volumes:
      - ./load-balancer/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    restart: always
    depends_on:
      database:
        condition: service_healthy

  database:
    build: ./database-draft
    deploy:
      mode: replicated
      replicas: ${DATABASE_REPLICAS}
    environment:
      SERVICE_PORT: 80
    command: npm run start --prefix /app
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1/healthcheck || exit 1"
      interval: 5s
      timeout: 2s
      retries: 5
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1

  tests:
    build: ./tests
    environment:
      SERVICE_URL: "http://proxy"
    # command: npm run test:dev --prefix /app
