version: "3.8"

services:
  load-balancer:
    build: ./load-balancer
    ports:
      - 80:80
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./load-balancer:/app
    working_dir: /app
    command: ["node", "/app/proxy.js"]
    networks:
      - db-nodes

  database:
    build: ./database-poc
    deploy:
      mode: replicated
      # replicas: ${DATABASE_REPLICAS}
      replicas: 4
    environment:
      SERVICE_PORT: 80 # Service HTTP port
      # MESH_NETWORK_URL: "http://proxy:80" # The url to join to the mesh (usually for production is the loadBalancer URL)
      LOG_LEVEL: 0 # Log level 0 to 4 (check service documentation)
    working_dir: /app
    command: npm run start
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1/healthcheck || exit 1"
      interval: 5s
      timeout: 2s
      retries: 5
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - db-nodes
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tests:
    build: ./tests
    environment:
      SERVICE_URL: "http://proxy"
    working_dir: /app
    # command: "npm run test"
    # command: "npm run stress"
    #    depends_on:
    #      - proxy
    networks:
      - db-nodes

networks:
  db-nodes:
    driver: bridge
